[project]
name = "ieee-sscs-sum-ting-wong-web-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "edge-tts>=7.2.8",
    "fastapi>=0.141.1",
    "google-genai>=2.16.0",
    "mediapipe>=1.0.0",
    "numpy>=2.5.1",
    "opencv-python>=5.0.0.93",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.52.0",
    "zeroconf>=0.150.0",
]
